# For more information see: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Madrid"
    reviewers:
      - beatrizsmerino
    assignees:
      - beatrizsmerino
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Madrid"
    reviewers:
      - beatrizsmerino
    assignees:
      - beatrizsmerino
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
