version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Madrid"
    reviewers:
      - beatriz sopeña merino
    assignees:
      - beatriz sopeña merino
    commit-message:
      prefix: NPM. Upgrade
      prefix-development: NPM. Upgrade
      include: ["*"]
      exclude: ["scope"]
      custom-message: " from {{from_version}} to {{to_version}}"
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Madrid"
    reviewers:
      - beatriz sopeña merino
    assignees:
      - beatriz sopeña merino
    commit-message:
      prefix: NPM. Upgrade
      prefix-development: NPM. Upgrade
      include: ["*"]
      exclude: ["scope"]
      custom-message: " from {{from_version}} to {{to_version}}"
